all:
  vars:
    codeserver_host_ip: 104.248.159.121
    codeserver_password: mypassword
    codeserver_domain: code-104.248.159.121.nip.io
  hosts:
    codeserver:
      ansible_host: "{{ codeserver_host_ip }}"
      ansible_conection: ssh
      ansible_user: root
      ansilbe_ssh_private_key_file: /home/fred/.ssh/id_rsa