- name: Install Nginx
  hosts: all
  tasks:
  - name: Check connectivity
    ping:
  - name: Install Nginx
    apt:
      update_cache: yes
      name: nginx
      state: present
  - name: Start Nginx
    systemd:
      enabled: yes
      state: started
      name: nginx