- name: Basic server test
  hosts: all
  vars:
    packages:
    - nginx
    - mysql-server
  tasks:
  - name: Check connectivity
    ping:
  - name: List facts on the servers
    setup:
  - name: Print server IP address
    debug:
      msg: "The current IP address is {{ ansible_host }}"
  - name: Install Nginx and mysql
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: latest
    loop: "{{ packages }}"
  - name: Enable nginx and mysql
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - nginx
    - mysql
  - name: List all files in /etc
    find:
      paths: /etc
      recurse: yes
    register: etc_files
  - name: Print all files in /etc
    debug:
      msg: "File: {{ item.path }}"
    loop: "{{ etc_files.files[1:2] }}"